version: "3.7"

services:
  node:
    image: node:18-alpine
    volumes:
      - ./:/project
    ports:
      - 3000:3000
    working_dir: /project
    entrypoint: ["tail", "-f", "/dev/null"]
    command: ["npm", "run", "start"]